### ISSUE TITLE
Allow end-user to edit fields

### ISSUE THREAD

**Issue by Lance-Inman** [dpsrr/ETA#4]
Allow users to edit the `rmaNumber`, `customer`, `unit`, and `warranty` fields of the traveler.

**Comment by Lance-Inman** [comment]
Still needed:
- allow users to edit Return `warranty`
- allow users to edit Diagnosis `warranty`
- allow users to edit Diagnosis `category`

**Comment by AtlasHands** [comment]
Added ability to edit Diagnosis Warranty and category in most recent push
